### ISSUE TITLE
Detailed tutorial

### ISSUE THREAD

**Issue by Maozaoaoo** [TFyre/bambu-farm#62] opened 2024-04-01 07:52 UTC
I am not very familiar with java compilation, but I am very interested in this project, so there are some detailed tutorials on running this project

**Comment by TFyre** [comment] 2024-04-01 08:28
You dont need to compile it, a compiled version is already provided in the releases section.

Did you check the [I just want to run it](https://github.com/TFyre/bambu-farm?tab=readme-ov-file#i-just-want-to-run-it) section in the readme?

How many of which model printers do you have?

**Comment by Maozaoaoo** [comment] 2024-04-01 14:41
Hi, I just confuse about the .env parts. And I have 5 p1p. Thx

**Comment by TFyre** [comment] 2024-04-01 15:31
You create multiple sections like the `myprinter1`

```properties
bambu.printers.myprinter1.device-id=REPLACE_WITH_DEVICE_SERIAL
bambu.printers.myprinter1.access-code=REPLACE_WITH_DEVICE_ACCESSCODE
bambu.printers.myprinter1.ip=REPLACE_WITH_DEVICE_IP

bambu.printers.myprinter2.device-id=REPLACE_WITH_DEVICE_SERIAL
bambu.printers.myprinter2.access-code=REPLACE_WITH_DEVICE_ACCESSCODE
bambu.printers.myprinter2.ip=REPLACE_WITH_DEVICE_IP

bambu.printers.myprinter3.device-id=REPLACE_WITH_DEVICE_SERIAL
bambu.printers.myprinter3.access-code=REPLACE_WITH_DEVICE_ACCESSCODE
bambu.printers.myprinter3.ip=REPLACE_WITH_DEVICE_IP
```

**Comment by Maozaoaoo** [comment] 2024-04-02 06:38
Hi, I have create the .evn but it does not run correctly.

**Comment by TFyre** [comment] 2024-04-02 06:57
You need to be more specific than that 😄

**Comment by TFyre** [comment] 2024-04-03 07:01
From the readme:
> If starting correctly, it will show `Routes startup (total:10 started:0 disabled:10)` with a number that is 2x your printer count

I dont think the file is called `.env`, its probably something like `env.txt`. please confirm?

from command prompt you can do `dir` to see the files and then `rename OLDNAME.BLAH .env` and restart the app

**Comment by Maozaoaoo** [comment] 2024-04-03 08:47
Thank you very much!

**Comment by TFyre** [comment] 2024-04-03 10:58
Sorted?

**Comment by tdw3d** [comment] 2024-04-26 01:44
I'm having the same issue, but I'm fairly sure I have the env correct:

$ ls
bambu-web-1.1.1-runner.jar  config.env

$ java -jar bambu-web-1.1.1-runner.jar
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2024-04-25 19:39:53,551 INFO  [org.apa.cam.uti.con.ThreadType] (main) The type of thread detected is PLATFORM
2024-04-25 19:39:53,829 INFO  [io.und.servlet] (main) Initializing AtmosphereFramework
2024-04-25 19:39:53,845 INFO  [com.vaa.flo.ser.sta.ServletDeployer] (main) Skipping automatic servlet registration because there is already a Vaadin servlet with the name com.vaadin.quarkus.QuarkusVaadinServlet
2024-04-25 19:39:53,852 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installed AtmosphereHandler com.vaadin.flow.server.communication.PushAtmosphereHandler mapped to context-path: /*
2024-04-25 19:39:53,853 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installed the following AtmosphereInterceptor mapped to AtmosphereHandler com.vaadin.flow.server.communication.PushAtmosphereHandler
2024-04-25 19:39:53,872 INFO  [org.atm.cpr.AtmosphereFramework] (main) Atmosphere is using org.atmosphere.util.VoidAnnotationProcessor for processing annotation
2024-04-25 19:39:53,875 INFO  [org.atm.uti.ForkJoinPool] (main) Using ForkJoinPool  java.util.concurrent.ForkJoinPool. Set the org.atmosphere.cpr.broadcaster.maxAsyncWriteThreads to -1 to fully use its power.
2024-04-25 19:39:53,879 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol
2024-04-25 19:39:53,881 INFO  [org.atm.con.JSR356AsyncSupport] (main) JSR 356 Mapping path /VAADIN/push
2024-04-25 19:39:53,882 INFO  [io.und.websockets] (main) UT026005: Adding programmatic server endpoint class org.atmosphere.container.JSR356Endpoint for path /VAADIN/push
2024-04-25 19:39:53,883 INFO  [io.und.websockets] (main) UT026005: Adding programmatic server endpoint class org.atmosphere.container.JSR356Endpoint for path /VAADIN/push/
2024-04-25 19:39:53,883 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installing Default AtmosphereInterceptors
2024-04-25 19:39:53,883 INFO  [org.atm.cpr.AtmosphereFramework] (main)  org.atmosphere.interceptor.CorsInterceptor : CORS Interceptor Support
2024-04-25 19:39:53,884 INFO  [org.atm.cpr.AtmosphereFramework] (main)  org.atmosphere.interceptor.CacheHeadersInterceptor : Default Response's Headers Interceptor
2024-04-25 19:39:53,884 INFO  [org.atm.cpr.AtmosphereFramework] (main)  org.atmosphere.interceptor.PaddingAtmosphereInterceptor : Browser Padding Interceptor Support
2024-04-25 19:39:53,884 INFO  [org.atm.cpr.AtmosphereFramework] (main)  org.atmosphere.interceptor.AndroidAtmosphereInterceptor : Android Interceptor Support
2024-04-25 19:39:53,885 INFO  [org.atm.cpr.AtmosphereFramework] (main)  org.atmosphere.interceptor.HeartbeatInterceptor : Heartbeat Interceptor Support
2024-04-25 19:39:53,885 INFO  [org.atm.cpr.AtmosphereFramework] (main)  org.atmosphere.interceptor.SSEAtmosphereInterceptor : SSE Interceptor Support
2024-04-25 19:39:53,885 INFO  [org.atm.cpr.AtmosphereFramework] (main)  org.atmosphere.interceptor.JSONPAtmosphereInterceptor : JSONP Interceptor Support
2024-04-25 19:39:53,886 INFO  [org.atm.cpr.AtmosphereFramework] (main)  org.atmosphere.interceptor.JavaScriptProtocol : Atmosphere JavaScript Protocol
2024-04-25 19:39:53,886 INFO  [org.atm.cpr.AtmosphereFramework] (main)  org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor : org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor
2024-04-25 19:39:53,886 INFO  [org.atm.cpr.AtmosphereFramework] (main)  org.atmosphere.interceptor.OnDisconnectInterceptor : Browser disconnection detection
2024-04-25 19:39:53,886 INFO  [org.atm.cpr.AtmosphereFramework] (main)  org.atmosphere.interceptor.IdleResourceInterceptor : org.atmosphere.interceptor.IdleResourceInterceptor
2024-04-25 19:39:53,886 INFO  [org.atm.cpr.AtmosphereFramework] (main) Set org.atmosphere.cpr.AtmosphereInterceptor.disableDefaults to disable them.
2024-04-25 19:39:53,886 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installed AtmosphereInterceptor CORS Interceptor Support with priority FIRST_BEFORE_DEFAULT
2024-04-25 19:39:53,886 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installed AtmosphereInterceptor Default Response's Headers Interceptor with priority AFTER_DEFAULT
2024-04-25 19:39:53,886 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installed AtmosphereInterceptor Browser Padding Interceptor Support with priority AFTER_DEFAULT
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installed AtmosphereInterceptor Android Interceptor Support with priority AFTER_DEFAULT
2024-04-25 19:39:53,887 INFO  [org.atm.int.HeartbeatInterceptor] (main) HeartbeatInterceptor configured with padding value 'X', client frequency 0 seconds and server frequency 60 seconds
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installed AtmosphereInterceptor Heartbeat Interceptor Support with priority AFTER_DEFAULT

2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installed AtmosphereInterceptor SSE Interceptor Support with priority AFTER_DEFAULT
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installed AtmosphereInterceptor JSONP Interceptor Support with priority AFTER_DEFAULT
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installed AtmosphereInterceptor Atmosphere JavaScript Protocol with priority AFTER_DEFAULT
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installed AtmosphereInterceptor org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor with priority AFTER_DEFAULT
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installed AtmosphereInterceptor Browser disconnection detection with priority AFTER_DEFAULT
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installed AtmosphereInterceptor org.atmosphere.interceptor.IdleResourceInterceptor with priority BEFORE_DEFAULT
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Using EndpointMapper class org.atmosphere.util.DefaultEndpointMapper
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Using BroadcasterCache: org.atmosphere.cache.UUIDBroadcasterCache
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Default Broadcaster Class: org.atmosphere.cpr.DefaultBroadcaster
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Broadcaster Shared List Resources: false
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Broadcaster Polling Wait Time 100
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Shared ExecutorService supported: true
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Messaging ExecutorService Pool Size unavailable - Not instance of ThreadPoolExecutor
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Async I/O Thread Pool Size: 200
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Using BroadcasterFactory: org.atmosphere.cpr.DefaultBroadcasterFactory
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Using AtmosphereResurceFactory: org.atmosphere.cpr.DefaultAtmosphereResourceFactory
2024-04-25 19:39:53,887 INFO  [org.atm.cpr.AtmosphereFramework] (main) Using WebSocketProcessor: org.atmosphere.websocket.DefaultWebSocketProcessor
2024-04-25 19:39:53,888 INFO  [org.atm.cpr.AtmosphereFramework] (main) Invoke AtmosphereInterceptor on WebSocket message true
2024-04-25 19:39:53,888 INFO  [org.atm.cpr.AtmosphereFramework] (main) HttpSession supported: true
2024-04-25 19:39:53,888 INFO  [org.atm.cpr.AtmosphereFramework] (main) Atmosphere is using org.atmosphere.inject.InjectableObjectFactory for dependency injection and object creation
2024-04-25 19:39:53,888 INFO  [org.atm.cpr.AtmosphereFramework] (main) Atmosphere is using async support: org.atmosphere.container.JSR356AsyncSupport running under container: Undertow - 5.2.1.Final using jakarta.servlet/3.0 and jsr356/WebSocket API
2024-04-25 19:39:53,888 INFO  [org.atm.cpr.AtmosphereFramework] (main) Atmosphere Framework 3.0.3.slf4jvaadin2 started.
2024-04-25 19:39:53,889 INFO  [org.atm.cpr.AtmosphereFramework] (main) Installed AtmosphereInterceptor  Track Message Size Interceptor using | with priority BEFORE_DEFAULT
2024-04-25 19:39:53,900 INFO  [com.vaa.flo.ser.DefaultDeploymentConfiguration] (main) Vaadin is running in production mode.
2024-04-25 19:39:54,112 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2024-04-25 19:39:54,113 INFO  [org.apa.cam.mai.MainSupport] (main) Apache Camel (Main) 4.4.0 is starting
2024-04-25 19:39:54,161 INFO  [com.tfy.bam.cam.CamelController] (main) configured
2024-04-25 19:39:54,170 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.4.0 (camel-1) is starting
2024-04-25 19:39:54,173 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup (started:0)
2024-04-25 19:39:54,173 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.4.0 (camel-1) started in 2ms (build:0ms init:0ms start:2ms)
2024-04-25 19:39:54,384 INFO  [io.quarkus] (main) bambu-web 1.1.1 on JVM (powered by Quarkus 3.8.2) started in 1.269s. Listening on: http://0.0.0.0:8080
2024-04-25 19:39:54,385 INFO  [io.quarkus] (main) Profile prod activated.
2024-04-25 19:39:54,385 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-direct, camel-paho, cdi, resteasy-reactive, resteasy-reactive-jackson, scheduler, security, servlet, smallrye-context-propagation, vaadin-quarkus, vertx, websockets, websockets-client]


$ 2024-04-25 19:40:17,218 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)                                                                               Apache Camel 4.4.0 (camel-1) is shutting down (timeout:45s)
2024-04-25 19:40:17,220 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes stopped (stopped:0)
2024-04-25 19:40:17,221 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.4.0 (camel-1) shutdown in 3ms (uptime:23s)
2024-04-25 19:40:17,224 INFO  [com.tfy.bam.pri.BambuPrintersImpl] (main) Stopping Printers
2024-04-25 19:40:17,228 INFO  [io.quarkus] (main) bambu-web stopped in 0.025s

**Comment by TFyre** [comment] 2024-04-26 05:12
@tdw3d please rename your config 😄 

```bash
mv config.env .env
```

**Comment by blasirio** [comment] 2024-05-05 02:16
I'm getting something similar

May 04, 2024 10:14:54 PM org.apache.camel.util.concurrent.ThreadType
INFO: The type of thread detected is PLATFORM
May 04, 2024 10:14:54 PM io.undertow.servlet
INFO: Initializing AtmosphereFramework
May 04, 2024 10:14:54 PM com.vaadin.flow.server.startup.ServletDeployer
INFO: Skipping automatic servlet registration because there is already a Vaadin servlet with the name com.vaadin.quarkus.QuarkusVaadinServlet
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereHandler com.vaadin.flow.server.communication.PushAtmosphereHandler mapped to context-path: /*
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed the following AtmosphereInterceptor mapped to AtmosphereHandler com.vaadin.flow.server.communication.PushAtmosphereHandler
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Atmosphere is using org.atmosphere.util.VoidAnnotationProcessor for processing annotation
May 04, 2024 10:14:54 PM org.atmosphere.util.ForkJoinPool
INFO: Using ForkJoinPool  java.util.concurrent.ForkJoinPool. Set the org.atmosphere.cpr.broadcaster.maxAsyncWriteThreads to -1 to fully use its power.
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol
May 04, 2024 10:14:54 PM org.atmosphere.container.JSR356AsyncSupport
INFO: JSR 356 Mapping path /VAADIN/push
May 04, 2024 10:14:54 PM io.undertow.websockets
INFO: UT026005: Adding programmatic server endpoint class org.atmosphere.container.JSR356Endpoint for path /VAADIN/push
May 04, 2024 10:14:54 PM io.undertow.websockets
INFO: UT026005: Adding programmatic server endpoint class org.atmosphere.container.JSR356Endpoint for path /VAADIN/push/
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installing Default AtmosphereInterceptors
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.CorsInterceptor : CORS Interceptor Support
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.CacheHeadersInterceptor : Default Response's Headers Interceptor
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.PaddingAtmosphereInterceptor : Browser Padding Interceptor Support
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.AndroidAtmosphereInterceptor : Android Interceptor Support
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.HeartbeatInterceptor : Heartbeat Interceptor Support
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.SSEAtmosphereInterceptor : SSE Interceptor Support
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.JSONPAtmosphereInterceptor : JSONP Interceptor Support
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.JavaScriptProtocol : Atmosphere JavaScript Protocol
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor : org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.OnDisconnectInterceptor : Browser disconnection detection
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO:   org.atmosphere.interceptor.IdleResourceInterceptor : org.atmosphere.interceptor.IdleResourceInterceptor
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Set org.atmosphere.cpr.AtmosphereInterceptor.disableDefaults to disable them.
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor CORS Interceptor Support with priority FIRST_BEFORE_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor Default Response's Headers Interceptor with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor Browser Padding Interceptor Support with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor Android Interceptor Support with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.interceptor.HeartbeatInterceptor
INFO: HeartbeatInterceptor configured with padding value 'X', client frequency 0 seconds and server frequency 60 seconds
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor Heartbeat Interceptor Support with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor SSE Interceptor Support with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor JSONP Interceptor Support with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor Atmosphere JavaScript Protocol with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor Browser disconnection detection with priority AFTER_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor org.atmosphere.interceptor.IdleResourceInterceptor with priority BEFORE_DEFAULT
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Using EndpointMapper class org.atmosphere.util.DefaultEndpointMapper
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Using BroadcasterCache: org.atmosphere.cache.UUIDBroadcasterCache
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Default Broadcaster Class: org.atmosphere.cpr.DefaultBroadcaster
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Broadcaster Shared List Resources: false
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Broadcaster Polling Wait Time 100
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Shared ExecutorService supported: true
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Messaging ExecutorService Pool Size unavailable - Not instance of ThreadPoolExecutor
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Async I/O Thread Pool Size: 200
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Using BroadcasterFactory: org.atmosphere.cpr.DefaultBroadcasterFactory
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Using AtmosphereResurceFactory: org.atmosphere.cpr.DefaultAtmosphereResourceFactory
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Using WebSocketProcessor: org.atmosphere.websocket.DefaultWebSocketProcessor
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Invoke AtmosphereInterceptor on WebSocket message true
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: HttpSession supported: true
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Atmosphere is using org.atmosphere.inject.InjectableObjectFactory for dependency injection and object creation
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Atmosphere is using async support: org.atmosphere.container.JSR356AsyncSupport running under container: Undertow - 5.2.1.Final using jakarta.servlet/3.0 and jsr356/WebSocket API
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Atmosphere Framework 3.0.3.slf4jvaadin2 started.
May 04, 2024 10:14:54 PM org.atmosphere.cpr.AtmosphereFramework
INFO: Installed AtmosphereInterceptor  Track Message Size Interceptor using | with priority BEFORE_DEFAULT
May 04, 2024 10:14:54 PM com.vaadin.flow.server.DefaultDeploymentConfiguration
INFO: Vaadin is running in production mode.
Configuration validation failed:
        java.lang.IllegalArgumentException: SRCFG00039: The config property bambu.printers.myprinter1.model with the config value "X1C" threw an Exception whilst being converted [X1C] cannot be converted to PrinterModel
        java.lang.IllegalArgumentException: SRCFG00039: The config property bambu.printers.myprinter2.model with the config value "A1" threw an Exception whilst being converted [A1] cannot be converted to PrinterModel
java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Failed to read configuration properties
        at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
        ... 7 more
Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
        java.lang.IllegalArgumentException: SRCFG00039: The config property bambu.printers.myprinter1.model with the config value "X1C" threw an Exception whilst being converted [X1C] cannot be converted to PrinterModel
        java.lang.IllegalArgumentException: SRCFG00039: The config property bambu.printers.myprinter2.model with the config value "A1" threw an Exception whilst being converted [A1] cannot be converted to PrinterModel
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:75)
        at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:84)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:724)
        at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
        at io.quarkus.runtime.generated.Config.createRunTimeConfig(Unknown Source)
        ... 8 more

**Comment by TFyre** [comment] 2024-05-05 06:30
@blasirio please check #77

**Comment by TFyre** [comment] 2024-05-22 08:23
Closing issue due to non activity

**Closed by TFyre** 2024-05-22 08:23 UTC
